---
services:
  rabbit:
    image: rabbitmq:3
    restart: always
    ports:
      - "5671:5671"
    networks:
      - amqp
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - /etc/ssl/rabbitmq:/etc/ssl/rabbitmq:ro
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      timeout: 10s
      interval: 30s
      retries: 3

  beaver:
    build: amqp-bridge
    restart: always
    networks:
      - amqp
      - internal
    environment:
      AMQP_SERVER: rabbit
    volumes:
      - ./amqp-bridge/app:/app:ro # dev purpose
    entrypoint: ["tail", "-f"] # dev purpose
    depends_on:
      rabbit:
        condition: service_healthy

  octopus:
    build: api
    restart: always
    ports:
      - "8080:8000"
    networks:
      - internal
    volumes:
      - database:/var/lib/sqlite:rw
      - ./api/app:/app:ro # dev purpose
    entrypoint: ["tail", "-f"] # dev purpose

  fox:
    build: web
    restart: always
    ports:
      - "80:8000"
      # - "443:443"
    volumes:
      - database:/var/lib/sqlite:ro
      - ./web/app:/app:ro # dev purpose
    entrypoint: ["tail", "-f"] # dev purpose
    depends_on:
      - octopus

networks:
  internal:
  amqp:

volumes:
  database:
