---
services:
  mosquitto:
    image: eclipse-mosquitto
    restart: always
    ports:
      - "1883:1883" # mqtt
      # - "9001:9001" # websockets
    networks:
      - warehouse
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro

  mqtt-bridge:
    image: local/warehouse-app
    build: .
    restart: always
    networks:
      - warehouse
    environment:
      WAREHOUSE_ID: DEMO
      API_SERVER: api.yousk.fr
    depends_on:
      - mosquitto

networks:
  warehouse:
