---
services:
  mosquitto:
    image: eclipse-mosquitto
    restart: always
    ports:
      - "1883:1883"
    networks:
      - warehouse
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro

  mqtt-bridge:
    build: .
    restart: always
    networks:
      - warehouse
    environment:
      WAREHOUSE_ID: DEMO
      API_SERVER: api.yousk.fr:8080
    # entrypoint: ["tail", "-f"] # dev purpose
    depends_on:
      - mosquitto

networks:
  warehouse:
