---
services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001" # what for?
    volumes:
      - "./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro"
    networks:
      - warehouse

  mqtt-bridge:
    image: local/warehouse-app
    build: .
    volumes:
      - "./app:/srv/app:ro" # for dev purpose
    networks:
      - warehouse
    depends_on:
      - mosquitto

networks:
  warehouse:
